# Generated by Django 2.2.3 on 2019-07-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='access_token',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
